### ISSUE TITLE
Restore ability to use STDIN

### ISSUE THREAD

**Issue by kesara** [ietf-tools/svgcheck#36]
Restore ability to use standard input for svgcheck.
This functionality was unintentionally removed in #28.

**Comment by larseggert** [comment]
We need a test suite :-)

**Comment by kesara** [comment]
> We need a test suite :-)

I assume you are talking about a test suite that covers all popular tools used by the community.

**Comment by rjsparks** [comment]
I really hope the path to redefining what svg is acceptable is opening. It would be a much better investment to build a more maintainable checker against _those_ rules than continuing to build infrastructure around a set of rules we know we're going to leave. (And to be explicit, I would expect to write something new for those rules rather than adjust this current implementation).

**Comment by hoehrmann** [comment]
The problem is this line https://github.com/ietf-tools/svgcheck/blob/40c2914c688de757b9e72560920dfd890ff0f8f9/svgcheck/run.py#L110 - it looks for a "stdin" file in the current working directory instead of reading from the moral equivalent of `/dev/stdin`.

(Via https://github.com/cabo/kramdown-rfc/issues/233)

**Comment by rfc2822** [comment]
> (Via [cabo/kramdown-rfc#233](https://github.com/cabo/kramdown-rfc/issues/233))

Replacing the line in `run.py` by

```
    if len(args) < 1:
        source = "/dev/stdin"
```

as mentioned there works for me.
